blogs/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns("",
    url(r'^$', "blogs.views.blog_index", name="home"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "blogs.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "blogs.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section_slug>[-\w]+)/$', "blogs.views.blog_section_list", name="blog_section"),
)

practical_exam/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = patterns(
    "",
    url(r"^admin/", include(admin.site.urls)),
    url(r"", include("blogs.urls")),
    url(r'^blogs/contact/$', "blogs.views.contact", name="contact"),
    url(r'^blogs/login/$', "blogs.views.login_view", name="login"),
    url(r'^blogs/logout/$', "blogs.views.logout_view", name="logout"),
    url(r'^blogs/signup/$', "blogs.views.register", name="register"),
    url(r'^blogs/post/$', "blogs.views.post", name="post"),
    url(r'^blogs/user_posts/$', "blogs.views.blog_user_posts", name="user_posts"),
    url(r'^blogs/update_post/(?P<post_pk>\d+)/$', "blogs.views.blog_update_post", name="update_post"),
    url(r'^blogs/delete_post/(?P<post_pk>\d+)/$', "blogs.views.blog_delete_post", name="delete_post"),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
# -*- coding: utf8 -*-
import json
import urllib2

from datetime import datetime

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.contrib.sites.models import Site

try:
    import twitter
except ImportError:
    twitter = None

from blogs.managers import PostManager
from blogs.settings import MARKUP_CHOICES
from blogs.utils import can_tweet

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

class Section(models.Model):
    name = models.CharField(max_length=140)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class Post(models.Model):
    section = models.ForeignKey(Section, related_name="posts")
    
    title = models.CharField(max_length=90)
    slug = models.SlugField()
    author = models.ForeignKey(User, related_name="posts")
    
    markup = models.CharField(max_length=25, choices=MARKUP_CHOICES)
    
    teaser_html = models.TextField(editable=False)
    content_html = models.TextField(editable=False)
    
    tweet_text = models.CharField(max_length=140, editable=False)
    
    created = models.DateTimeField(default=datetime.now, editable=False) # when first revision was created
    updated = models.DateTimeField(null=True, blank=True, editable=False) # when last revision was create (even if not published)
    published = models.DateTimeField(null=True, blank=True, editable=False) # when last published
    
    view_count = models.IntegerField(default=0, editable=False)

    def rev(self, rev_id):
        return self.revisions.get(pk=rev_id)
    
    def current(self):
        "the currently visible (latest published) revision"
        return self.revisions.exclude(published=None).order_by("-published")[0]
    
    def latest(self):
        "the latest modified (even if not published) revision"
        try:
            return self.revisions.order_by("-updated")[0]
        except IndexError:
            return None
    
    class Meta:
        ordering = ("-published",)
        get_latest_by = "published"
    
    objects = PostManager()
    
    def __unicode__(self):
        return self.title
    
    def as_tweet(self):
        if not self.tweet_text:
            current_site = Site.objects.get_current()
            api_url = "http://api.tr.im/api/trim_url.json"
            u = urllib2.urlopen("%s?url=http://%s%s" % (
                api_url,
                current_site.domain,
                self.get_absolute_url(),
            ))
            result = json.loads(u.read())
            self.tweet_text = u"%s %s — %s" % (
                settings.TWITTER_TWEET_PREFIX,
                self.title,
                result["url"],
            )
        return self.tweet_text
    
    def tweet(self):
        if can_tweet():
            account = twitter.Api(
                username = settings.TWITTER_USERNAME,
                password = settings.TWITTER_PASSWORD,
            )
            account.PostUpdate(self.as_tweet())
        else:
            raise ImproperlyConfigured("Unable to send tweet due to either "
                "missing python-twitter or required settings.")
    
    def save(self, **kwargs):
        self.updated_at = datetime.now()
        super(Post, self).save(**kwargs)
    
    def get_absolute_url(self):
        if self.published:
            name = "blog_post"
            kwargs = {
                "year": self.published.strftime("%Y"),
                "month": self.published.strftime("%m"),
                "day": self.published.strftime("%d"),
                "slug": self.slug,
            }
        else:
            name = "blog_post_pk"
            kwargs = {
                "post_pk": self.pk,
            }
        return reverse(name, kwargs=kwargs)
    
    def inc_views(self):
        self.view_count += 1
        self.save()
        self.current().inc_views()


class Revision(models.Model):
    
    post = models.ForeignKey(Post, related_name="revisions")
    
    title = models.CharField(max_length=90)
    teaser = models.TextField()
    
    content = models.TextField()
    
    author = models.ForeignKey(User, related_name="revisions")
    
    updated = models.DateTimeField(default=datetime.now)
    published = models.DateTimeField(null=True, blank=True)
    
    view_count = models.IntegerField(default=0, editable=False)
    
    def __unicode__(self):
        return 'Revision %s for %s' % (self.updated.strftime('%Y%m%d-%H%M'), self.post.slug)
    
    def inc_views(self):
        self.view_count += 1
        self.save()


class Image(models.Model):
    
    post = models.ForeignKey(Post, related_name="images")
    
    image_path = models.ImageField(upload_to="images/%Y/%m/%d")
    url = models.CharField(max_length=150, blank=True)
    
    timestamp = models.DateTimeField(default=datetime.now, editable=False)
    
    def __unicode__(self):
        if self.pk is not None:
            return "{{ %d }}" % self.pk
        else:
            return "deleted image"


class FeedHit(models.Model):
    
    request_data = models.TextField()
    created = models.DateTimeField(default=datetime.now)

blogs/views.py
from datetime import datetime

from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import simplejson as json

from blogs.models import FeedHit, Post, Section
from blogs.settings import ALL_SECTION_NAME
from blogs.signals import post_viewed

from django import forms
from blogs.forms import ContactForm, LoginForm, UserProfileForm, UserForm, UserPostForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


@login_required(login_url='/blogs/login/')
def blog_user_posts(request):
    user_posts = Post.objects.current()

    sections = Section.objects.all()

    return render_to_response("blogs/blog_user_posts.html", {
        "user_posts": user_posts,
        'sections':sections
    }, context_instance=RequestContext(request))


@login_required(login_url='/blogs/login/')
def blog_update_post(request, post_pk):    
    context = RequestContext(request)
    post = Post.objects.get(pk=post_pk)

    sections = Section.objects.all()

    posted = False

    if request.method == 'POST':
        post_form = UserPostForm(request.POST, instance=post)

        if post_form.is_valid():
            post_form.save()

            posted = True
        else:
            print post_form.errors

    else:
        if post:
            post_form = UserPostForm(instance=post)
        else:
            post_form = UserPostForm()

    return render_to_response(
            'blogs/update.html',
            {'post_form': post_form, 'posted': posted, 'post':post, 'sections':sections},
            context)


@login_required(login_url='/blogs/login/')
def blog_delete_post(request, post_pk):    
    post = Post.objects.get(pk=post_pk)

    sections = Section.objects.all()

    if post:
        post.delete()
        
    else:
        pass

    user_posts = Post.objects.current()

    return render_to_response("blogs/blog_user_posts.html", {
        "user_posts": user_posts,
        'sections':sections
    }, context_instance=RequestContext(request))


def post(request):
    
    context = RequestContext(request)

    sections = Section.objects.all()

    posted = False

    if request.method == 'POST':
        user_post_form = UserPostForm(data=request.POST)

        if user_post_form.is_valid():
            user_post = user_post_form.save()

            user_post.save()

            posted = True
    else:
        user_post_form = UserPostForm()
        
    return render_to_response(
            'blogs/post.html',
            {'user_post_form': user_post_form, 'posted': posted, 'sections':sections},
            context)


def register(request):
    
    context = RequestContext(request)

    sections = Section.objects.all()

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response(
            'blogs/signup.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered, 'sections':sections},
            context)


def login_view(request):
    context = {}
    context['check_errors'] = False

    sections = Section.objects.all()
     
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
     
            user = authenticate(username=username, password=password)
     
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    context['check_errors'] = True
                    pass
            else:
                context['check_errors'] = True
                pass
     
            return HttpResponseRedirect('/')
    else:
        form = LoginForm()
     
    return render(request, 'blogs/login.html', { 'form': form, 'sections':sections})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def contact(request):

    sections = Section.objects.all()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
     
            recipients = ['iamgaude@gmail.com']
            if cc_myself:
                recipients.append(sender)
     
            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
     
            return HttpResponseRedirect('/')
        else:
            ContactForm(request.POST)
    else:
        form = ContactForm()
     
    return render(request, "blogs/contact.html", {'form': form, 'sections':sections})

@login_required(login_url='/blogs/login/')
def blog_index(request):
    
    posts = Post.objects.current()

    sections = Section.objects.all()
    
    return render_to_response("blogs/blog_list.html", {
        "posts": posts,
        'sections':sections
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def blog_section_list(request, section_slug):
    
    section = get_object_or_404(Section, slug=section_slug)
    posts   = section.posts.all()

    sections = Section.objects.all()

    return render_to_response("blogs/blog_section_list.html", {
        "section_slug": section_slug,
        "section_name": section.name,
        "posts": posts,
        'sections':sections
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def blog_post_detail(request, **kwargs):
    
    sections = Section.objects.all()

    if "post_pk" in kwargs:
        if request.user.is_authenticated() and request.user.is_staff:
            queryset = Post.objects.all()
            post = get_object_or_404(queryset, pk=kwargs["post_pk"])
        else:
            raise Http404()
    else:
        queryset = Post.objects.current()
        queryset = queryset.filter(
            published__year = int(kwargs["year"]),
            published__month = int(kwargs["month"]),
            published__day = int(kwargs["day"]),
        )
        post = get_object_or_404(queryset, slug=kwargs["slug"])
        post_viewed.send(sender=post, post=post, request=request)
    
    return render_to_response("blogs/blog_post.html", {
        "post": post,
        'sections':sections
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def serialize_request(request):

    data = {
        "path": request.path,
        "META": {
            "QUERY_STRING": request.META.get("QUERY_STRING"),
            "REMOTE_ADDR": request.META.get("REMOTE_ADDR"),
        }
    }
    for key in request.META:
        if key.startswith("HTTP"):
            data["META"][key] = request.META[key]
    return json.dumps(data)

@login_required(login_url='/blogs/login/')
def blog_feed(request, section=None):
    
    section = get_object_or_404(Section, slug=section)
    posts = Post.objects.filter(section=section)

    sections = Section.objects.all()

    if section is None:
        section = Section.objects.values_list('name', flat=True).order_by('name')

    current_site = Site.objects.get_current()
    
    feed_title = "%s Blog: %s" % (current_site.name, section[0].upper() + section[1:])
    
    blog_url = "http://%s%s" % (current_site.domain, reverse("blog"))
    
    url_name, kwargs = "blog_feed", {"section": section}
    feed_url = "http://%s%s" % (current_site.domain, reverse(url_name, kwargs=kwargs))
    
    if posts:
        feed_updated = posts[0].published
    else:
        feed_updated = datetime(2009, 8, 1, 0, 0, 0)
    
    # create a feed hit
    hit = FeedHit()
    hit.request_data = serialize_request(request)
    hit.save()
    
    atom = render_to_string("blogs/atom_feed.xml", {
        "feed_id": feed_url,
        "feed_title": feed_title,
        "blog_url": blog_url,
        "feed_url": feed_url,
        "feed_updated": feed_updated,
        "entries": posts,
        "current_site": current_site,
        'sections':sections
    })
    return HttpResponse(atom, mimetype="application/atom+xml")

practical_exam/templates/blogs/blog_base.html
{% extends "site_base.html" %}

{% block body_class %}blog{% endblock %}


{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
            {% if user.is_authenticated %}
                <h1>
                    Welcome, {{ request.user.get_username }}!
                </h1>
                <p class="lead"><p>

                <br>
                Your full name is <u>{{ request.user.get_full_name }}</u>
                <br>
                Your email address is <u>{{ request.user.email }}</u>
                <br>
                <br>
                <br>

                Manage your posts:
                <ul>

                <li> <a href="{% url 'post' %}"><u>Add new post</u></a></li>
                <li> <a href="{% url 'user_posts' %}"><u>Update and Delete post</u></a></li> 
            
                </ul>  

                </p>
                </p>
                
            {% endif %}       
            {% endblock %}
        </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_list.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ post.title }} &mdash; {{ SITE_NAME }}{% endblock %}

{% block extra_head %}
    <meta name="description" content="{{ post.teaser_html|striptags }}">
    <meta name="og:title" content="{{ post.title }}">
    <meta name="og:description" content="{{ post.teaser_html|striptags }}">
{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="post">
            <h1>{{ post.title }}</h1>
            {% include "blogs/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div class="content">{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_section_list.html
{% extends "blogs/blog_base.html" %}


{% block head_title %}{{ SITE_NAME }} ({{ section_name }}){% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {% include "blogs/dateline.html" %}
                <div class="teaser">{{ post.teaser_html|safe }}</div>
                <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published in this section.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_user_posts.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
	
    {% if user_posts %}   
	    <div class="post-list">

	        {% for post in user_posts %}
	        	{% if post.author.username == request.user.username %}
		            <div class="post">
		                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
		                {% include "blogs/dateline.html" %}
		                <div class="teaser">{{ post.teaser_html|safe }}</div>
		                <p class="more">
		                	<a href="{{ post.get_absolute_url }}" class="post-link">read more...</a>
		                </p>

		                <a href="/blogs/update_post/{{ post.id }}/">
                        		<button>Update Post</button>
                        </a>

                  		<a href="/blogs/delete_post/{{ post.id }}/">
                        		<button>Delete Post</button>
                  		</a>
                  		<br />
		            </div>
				{% endif %}
	        {% endfor %}

	    </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/contact.html
{% extends "blogs/blog_base.html" %}

{% block body_class %}blog{% endblock %}


{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
                <h1>
                    <a href="">Contact Us</a>
                </h1>
            {% endblock %}
            {% block page %}
            <form action="/blogs/contact/" method="post">
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" value="Submit" />
			</form>
			{% endblock %}
            </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/dateline.html
<p class="post_dateline">
    <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
    <br />
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/templates/blogs/dateline_stale.html
<p class="post_dateline">
    {% if not post.stale %}
        <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
        <br />
    {% endif %}
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/templates/blogs/login.html
{% extends "blogs/blog_base.html" %}



{% block body_class %}blog{% endblock %}


{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
                <h1>
                    <a href="#">Login</a>
                </h1>
            {% endblock %}

            <form action="/blogs/login/" method="post">
            {% csrf_token %}
            <table>
            	{% if form.errors%}
				<i> <h1>invalid</h1> </i>
				{% endif %}
				
				<tr>
					<td>{{ form.username.label_tag}}</td>
					<td>{{ form.username }}</td>
				</tr>
				<tr>
					<td>{{ form.password.label_tag}}</td>
					<td>{{ form.password }}</td>
				</tr>
				


			</table>
			
			
			<!-- {{form.as_p}} -->
			<input type="submit" value="Submit" />
			</form>
			
			
            </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/post.html
{% extends "site_base.html" %}

{% block title %}Create Post{% endblock %}

{% block body %}

        <h1>Create post</h1>
        {% if posted %}
        <strong>You have successfully created a post.</strong>
        <a href="/">Return to the homepage?</a><br />
        {% else %}
        <form id="user_form" method="post" action=""
                enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_post_form.as_p }}
            
            <input type="submit" name="submit" value="Post" />
        </form>
        {% endif %}

        
{% endblock %}

practical_exam/templates/blogs/signup.html
{% extends "site_base.html" %}

{% block title %}Sign up{% endblock %}

{% block body %}

        <h1>Sign up!</h1>

        {% if registered %}
        <strong>You have already signed up.</strong>
        <a href="/">Return to the homepage?</a><br />
        {% else %}
        <form id="user_form" method="post" action=""
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
     
            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Sign Up" />
        </form>
        {% endif %}

        
{% endblock %}

practical_exam/templates/blogs/update.html
{% extends "site_base.html" %}
{% block body%}

<h1>Update Post</h1>

    {% if posted %}
        {% csrf_token %}
       <strong>Your post was successfully updated!</strong>
       <a href="/">Return to the homepage.</a><br />
       {% else %}
        <form id="post_form" method="post" action="/blogs/update_post/{{post.id}}/" 
            enctype="multipart/form-data">
           {% csrf_token %}
            {{ post_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Update" />
        </form>
    {% endif %}
{% endblock %}